# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: custom
  theme_night:
  font: custom
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'UKDRI Neurogenomics lab at Imperial College Department of Brain Sciences'
    twitter: 'n_skene'
  analytics:
    google_analytics: 'UA-175929032-2'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Neurogenomics Lab.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  # Adding institute logos to the footer
  # images:
  #   - path: /assets/media/dri_logo_footer.png
  #   - path: /assets/media/imperial_logo_footer.png

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/neurogenomics/neurogenomics-lab-website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapbox'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

icon.pack:
  ai: true
